type:
  - Desktop App
status: In Progress

technologies:
  - Electron
  - React
  - Python
  - FastAPI
  - TypeScript
  - Faster Whisper AI
  - Materiaul UI

banner: .github/assets/lrcify_gif.gif

video: .github/assets/lrcify_video.mp4

gallery:
  - .github/assets/screenshot-01.png
  - .github/assets/screenshot-02.png
  - .github/assets/screenshot-03.png
  - .github/assets/screenshot-04.png
  - .github/assets/screenshot-05.png
  - .github/assets/screenshot-06.png
  - .github/assets/screenshot-07.png
  - .github/assets/screenshot-08.png
